name: Terraform Destroy

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

env:
  AWS_REGION: "eu-north-1"
  TF_VERSION: "1.2.8"
  PREFIX: "kodak-lab"
  AWS_ACCOUNT_ID: "zzz"

permissions:
  id-token: write
  contents: read

jobs:
  tf_destroy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        folder: ["demo", "blah"]

    defaults:
      run:
        working-directory: "terraform/${{ matrix.folder }}"

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.PREFIX }}-github-oidc
        role-session-name: ${{ env.PREFIX }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Install
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -auto-approve